# DEVELOPMENT CONFIGURATION FILE
# USAGE: export environment variable BEETSDIR=/path/to/BEETSDIR
# then: `beets config -p` should list this file

directory: Music
library: library.db
asciify_paths: yes
id3v23: yes

pluginpath:
    - ~/Documents/Projects/Python/BeetsPluginXtractor/beetsplug

plugins:
    - info
    - xtractor

format_item: "[format:$format][bpm:$bpm][gender:$gender] ::: $artist:$title"

import:
    copy: yes
    autotag: no

xtractor:
    auto: no
    dry-run: no
    write: yes
    threads: 2
    force: no
    quiet: no
    items_per_run: 1
    keep_output: yes
    output_path: /Users/jackisback/Documents/Projects/Python/BeetsPluginXtractor/BEETSDIR/ee
    low_level_extractor: /Users/jackisback/Documents/Projects/Python/BeetsPluginXtractor/BEETSDIR/essentia/extractors/osx_x86_64_streaming_extractor_music
    high_level_extractor: /Users/jackisback/Documents/Projects/Python/BeetsPluginXtractor/BEETSDIR/essentia/extractors/osx_x86_64_streaming_extractor_music_svm

