# DEVELOPMENT CONFIGURATION FILE
# USAGE: export environment variable BEETSDIR=/path/to/BEETSDIR
# then: `beets config -p` should list this file

#directory: /Volumes/J/Music/
#library: ~/.config/beets/real_library.db
directory: Music
library: library.db

asciify_paths: yes
id3v23: yes

pluginpath:
    - ~/Documents/Projects/Python/BeetsPluginXtractor/beetsplug

plugins:
    - info
    - xtractor

format_item: "[format:$format][bpm:$bpm][gender:$gender] ::: $artist:$title"

import:
    copy: yes
    autotag: no

xtractor:
    auto: no
    dry-run: no
    write: yes
    threads: 1
    force: no
    quiet: no
    items_per_run: 0
    keep_output: yes
    keep_profiles: no
    output_path: /Users/jackisback/Documents/Projects/Python/BeetsPluginXtractor/BEETSDIR/xtraction
    low_level_extractor: /Users/jackisback/Documents/Projects/Other/extractors/beta5/essentia_streaming_extractor_music
    high_level_extractor: /Users/jackisback/Documents/Projects/Other/extractors/beta5/essentia_streaming_extractor_music_svm
    high_level_profile:
        highlevel:
            svm_models:
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/danceability.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/gender.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/genre_rosamerica.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/mood_acoustic.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/mood_aggressive.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/mood_electronic.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/mood_happy.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/mood_party.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/mood_relaxed.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/mood_sad.history
                - /Users/jackisback/Documents/Projects/Other/extractors/svm_models_beta5/voice_instrumental.history
